import { user } from "@/models/better-auth/auth.model";
import { type InvitationStatus } from "better-auth/plugins";
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";

/* * * * * * * * * *
 * !! DO NOT EDIT !!
 * This file is automatically generated by BetterAuth - Organization Plugin.
 * Unless you know what you're doing, you should not edit this file directly.
 *
 * NOTE: If you need to extend the core schema, please check the documentation:
 * https://www.better-auth.com/docs/concepts/database#extending-core-schema
 *
 * !! DO NOT EDIT !!
 * * * * * * * * * *
 */

const DEFAULT_INVITATION_STATUS: InvitationStatus = "pending";

export const organization = pgTable("organization", {
  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * * * DO NOT EDIT - START  (fields required by BetterAuth - Organization Plugin * * *
   * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").unique(),
  logo: text("logo"),
  createdAt: timestamp("created_at").notNull(),
  metadata: text("metadata"),
  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * * *  DO NOT EDIT - END  (fields required by BetterAuth - Organization Plugin  * * *
   * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
});
export type OrganizationSelect = typeof organization.$inferSelect;

export const member = pgTable("member", {
  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * * * DO NOT EDIT - START  (fields required by BetterAuth - Organization Plugin * * *
   * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
  id: text("id").primaryKey(),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  role: text("role").default("member").notNull(),
  createdAt: timestamp("created_at").notNull(),
  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * * *  DO NOT EDIT - END  (fields required by BetterAuth - Organization Plugin  * * *
   * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
});

export const invitation = pgTable("invitation", {
  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * * * DO NOT EDIT - START  (fields required by BetterAuth - Organization Plugin * * *
   * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
  id: text("id").primaryKey(),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  email: text("email").notNull(),
  role: text("role"),
  status: text("status").default(DEFAULT_INVITATION_STATUS).notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  inviterId: text("inviter_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
   * * *  DO NOT EDIT - END  (fields required by BetterAuth - Organization Plugin  * * *
   * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
});
